# Generated by Django 4.2.1 on 2023-06-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('synopsis', models.CharField(max_length=1000)),
                ('prix', models.FloatField()),
                ('qt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('qt', models.IntegerField()),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.adherent')),
                ('liv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.livre')),
                ('man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.manager')),
            ],
        ),
        migrations.CreateModel(
            name='empreinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('returned', models.BooleanField()),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.adherent')),
                ('liv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.livre')),
                ('man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.manager')),
            ],
        ),
    ]
