# Generated by Django 4.2.1 on 2023-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreinte',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
