# Generated by Django 4.2.1 on 2023-06-05 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_alter_empreinte_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreinte',
            name='begin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
