# Generated by Django 4.2.1 on 2023-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_alter_empreinte_begin_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='adherent',
            name='password',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
