# Generated by Django 4.2.1 on 2023-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_transaction_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
